name: Npm publish

on:
  push:
    branches:
      - master
    paths:
      - package.json

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: primer/publish@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
